# Generated by Django 5.0.2 on 2024-03-11 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='allow_register',
            new_name='allowRegister',
        ),
        migrations.RenameField(
            model_name='registerconfig',
            old_name='require_register_perms',
            new_name='requireRegisterPerms',
        ),
    ]
