# Generated by Django 5.0.2 on 2024-03-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followrequest',
            name='requester',
            field=models.CharField(max_length=200),
        ),
    ]
