# Generated by Django 5.0.2 on 2024-03-11 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_allow_register_author_allowregister_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='allowRegister',
            field=models.BooleanField(default=False),
        ),
    ]
