# Generated by Django 5.0.2 on 2024-03-19 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_follow_follower_follower_unique_follower'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='summary',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
