# Generated by Django 5.0.2 on 2024-03-19 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_follow_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='summary',
        ),
    ]
