# Generated by Django 5.0.2 on 2024-02-16 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('commentid', models.TextField(db_column='commentID', primary_key=True, serialize=False)),
                ('contenttype', models.TextField(db_column='contentType')),
                ('content', models.TextField()),
                ('comment', models.TextField()),
                ('publishdate', models.DateTimeField(db_column='publishDate')),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('authorid', models.TextField(db_column='authorID', primary_key=True, serialize=False)),
                ('followerid', models.TextField(db_column='followerID')),
            ],
            options={
                'db_table': 'following',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('authorid', models.OneToOneField(db_column='authorID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.TextField()),
                ('postid', models.TextField(db_column='postID', primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('origin', models.TextField()),
                ('description', models.TextField()),
                ('contenttype', models.TextField(db_column='contentType')),
                ('content', models.TextField()),
                ('commentcount', models.IntegerField(blank=True, db_column='commentCount', null=True)),
                ('publishdate', models.DateTimeField(db_column='publishDate')),
                ('visibility', models.TextField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
