# Generated by Django 5.0.2 on 2024-02-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('title', models.TextField()),
                ('postid', models.TextField(db_column='postID', primary_key=True, serialize=False)),
                ('source', models.TextField()),
                ('origin', models.TextField()),
                ('description', models.TextField()),
                ('contenttype', models.TextField(db_column='contentType')),
                ('content', models.TextField()),
                ('commentcount', models.IntegerField(blank=True, db_column='commentCount', null=True)),
                ('publishdate', models.DateTimeField(db_column='publishDate')),
                ('visibility', models.TextField()),
            ],
            options={
                'db_table': 'posts',
                'managed': False,
            },
        ),
    ]
