# Generated by Django 5.0.2 on 2024-03-11 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(db_column='content', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='contentType',
            field=models.TextField(db_column='contentType', null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='count',
            field=models.IntegerField(blank=True, db_column='commentCount', default=0, null=True),
        ),
    ]
