# Generated by Django 5.0.2 on 2024-03-10 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='authorname',
        ),
        migrations.RemoveField(
            model_name='post',
            name='authorprofile',
        ),
    ]
