# Generated by Django 5.0.2 on 2024-03-20 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='author',
        ),
        migrations.RemoveField(
            model_name='likepost',
            name='post',
        ),
        migrations.AlterModelOptions(
            name='like',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.comment'),
        ),
        migrations.DeleteModel(
            name='LikeComment',
        ),
        migrations.DeleteModel(
            name='LikePost',
        ),
    ]
