# Generated by Django 5.0.2 on 2024-02-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='linked_img_post',
            field=models.TextField(blank=True, verbose_name='self'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='source',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='title',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.TextField(null=True),
        ),
    ]
