# Generated by Django 5.0.2 on 2024-02-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_linked_img_post_alter_posts_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='linked_img_post',
            field=models.TextField(blank=True, null=True, verbose_name='self'),
        ),
    ]
