# Generated by Django 5.0.2 on 2024-03-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_linked_img_post_post_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='authorprofile',
            field=models.TextField(null=True),
        ),
    ]
