# Generated by Django 5.0.2 on 2024-02-25 03:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_posts_linked_img_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='postid',
            field=models.UUIDField(db_column='postID', default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
