# Generated by Django 5.0.2 on 2024-03-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_authorprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='authorprofile',
            field=models.URLField(null=True),
        ),
    ]
