# Generated by Django 5.0.2 on 2024-02-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_posts_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='authorname',
            field=models.TextField(null=True),
        ),
    ]
