# Generated by Django 5.0.2 on 2024-03-16 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('sender_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver_id', models.CharField(max_length=200, null=True)),
                ('post_id', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
